#!/bin/sh
#------------------------------------------------------------------------------
# $Id: git-promote,v 1.14 2013/09/09 11:01:32 bosisio Exp $
#------------------------------------------------------------------------------

function Info {
  printf '\t[30;41m %s ... [m\n' "$@"
}

#------------------------------------------------------------------------------

function SubInfo {
  printf '\t\t[33;40m %s ... [m\n' "$@"
}

#------------------------------------------------------------------------------

function Usage {
  local PROGRAM=$(basename $0 | /bin/sed 's/-/ /')
  /bin/cat >&2 << HERE

	[1;7m USAGE: ${PROGRAM} [-m <commit-message>] [--test] [--no-interact] [m
			   [1;7m [--already-in=<branch>] [--skip-from=<branch>] [m
			   [1;7m [--backward=<branch>] [--edit] [m
                           [1;7m [-stay=<branch>] [-author=<username>] [m

		Merge current branch into all subsequent branches,
		one by one and in the proper order.
		Commit message will include given message, beside merge info.
		A preliminary 'pull' on all subsequent branches is
		automatically performed; at the end, current branch and all
		subsequent ones are pushed to the remote repository.
		Each merge step includes running 'git mergetool' if needed
		and can be verifyed or stopped before it is completed.

	 -m "<commit-msg>" : if omitted, message is taken from last commit
	 --test            : just print the commands, instead of executing them
	 --no-interact     : do not ask for confirmation after each merge
	 --already-in=<br> : when branch <br> reached, do "merge -X ours" and
                             stop (since change is ALREADY PRESENT in <br>)
	 --skip-from=<br>  : when branch <br> reached, do "merge -s ours" and
                             stop (since change is NOT DESIRED in <br>)
	 --backward=<br>   : cherry-pick last commit to branch <br> and then
			     promote (implies "--already-in=<current-branch>")
	 --edit            : let the user modify the files after each merge step
         -stay=<br>        : leave <br> active (do not go back to original one)
	 -author=<user>    : use given <username> as author (name and e-mail)

HERE
  exit $1
}

#------------------------------------------------------------------------------

function ask_for_confirmation {
  local MSG="$1"
  local FORCE="$2"
  [ "${NON_INTERACTIVE}" -a -z "${FORCE}" ] && return 0
  local ANSWER
  while /bin/true; do
    printf '%s [Y/N] » ' "${MSG}"
    read ANSWER
    case "${ANSWER}" in
      y|Y) return 0 ;;
      n|N) return 1 ;;
      *) # Repeat the loop
    esac
  done
}

#------------------------------------------------------------------------------

function run_git_commit {
  local COMMIT_MSG="$1"
  if [ "${GIT_AUTHOR}" ]; then
    ${RUN} git commit -m "${COMMIT_MSG}" "${GIT_AUTHOR}"
  else
    ${RUN} git commit -m "${COMMIT_MSG}"
  fi
  if [ $? -ne 0 ]; then
    printf 'ERROR: "git commit" failed - merge aborted !\n' >&2
    exit 3
  fi
}

#------------------------------------------------------------------------------

function do_git_merge {
  local NEW_REV="$1"
  local OLD_REV="$2"
  local MSG="$3"
  local MERG_TYPE="$4"
  local OPTS="$5"
  local B='[30;42m'
  local N='[m'

  SubInfo "Checking-out branch '${NEW_REV}'"
  ${RUN} git checkout "${NEW_REV}"

  #SubInfo "Re-running 'git pull' to make sure branch is aligned"
  #${RUN} git pull

  SubInfo "Merging branch '${OLD_REV}' into '${NEW_REV}'"
  ${RUN} git merge "${OLD_REV}" --no-commit ${OPTS}

  SubInfo "Showing 'git status'"
  ${RUN} git status -uno

  SubInfo "Running 'git mergetool' if needed"
  ${RUN} git mergetool

  if [ "${EDIT_MERGE}" ]; then
    ask_for_confirmation 'Do you want to edit merged files before proceeding ?'
    if [ $? -eq 0 ]; then # Answer is 'Y'
      local FILES=$(git status | \
                    /bin/awk '/modified:|new file:/{ printf "%s ",$3 }')
      ${RUN} ${EDITOR:-vi} ${FILES}
      printf '\tPress ENTER to continue ...\n'
      read
      ${RUN} git add ${FILES}
    fi
  fi

  printf "\nYou can now ${B}commit${N} the merge, leave it ${B}pending${N}"
  printf " or ${B}abort${N} it.\n"
  ask_for_confirmation 'Proceed with merge ?'
  if [ $? -ne 0 ]; then # Answer is 'N'
    printf 'OK, going to stop the "promote" process.\n'
    printf 'But what do you want to do with current merge step?\n'
    printf ' - cancel it (you need to REDO the merge manually then !)\n'
    printf ' - leave it pending (you can make changes and commit the merge).\n'
    ask_for_confirmation 'Undo merge and revert to original state ?'
    if [ $? -eq 0 ]; then # Second answer is 'Y'
      Info "Undoing merge with 'git merge --abort'"
      ${RUN} git merge --abort
      Info "Re-showing 'git status'"
      ${RUN} git status -uno
    else  # Second answer is 'N'
      printf '\nWARNING: leaving the merge pending as requested !\n\t '
      printf '(complete with "git commit" or undo with "git merge --abort")\n\n'
    fi
    exit 2
  fi

  SubInfo "Running 'git commit' to conclude merge"
  run_git_commit "${MERG_TYPE}ed ${OLD_REV} into ${NEW_REV} (${MSG})"
}

#------------------------------------------------------------------------------

function git_ff_merge {
  local BRANCH="$1"
  local COMMIT="$2"

  local BRANCH_HASH=$(git show-ref -s --verify "refs/heads/${BRANCH}" 2>/dev/null)
  if [ $? -ne 0 ]; then
    printf "Error: unknown BRANCH ${BRANCH}\n" >&2
    return 1
  fi

  local COMMIT_HASH=$(git rev-parse --verify --quiet "${COMMIT}")
  if [ $? -ne 0 ]; then
    printf "Error: unknown revision ${COMMIT}\n" >&2
    return 2
  fi

  local BASE_HASH=$(git merge-base "${BRANCH_HASH}" "${COMMIT_HASH}")
  if [ "${BASE_HASH}" != "${BRANCH_HASH}" ]; then
    printf "WARNING: merging ${COMMIT} into ${BRANCH} would not be a fast-forward\n" >&2
    return 3
  fi
  local BRANCH_SHORT_HASH=$(echo "${BRANCH_HASH}" | sed 's/^\(.......\).*$/\1/')
  local COMMIT_SHORT_HASH=$(echo "${COMMIT_HASH}" | sed 's/^\(.......\).*$/\1/')
  printf "Updating ${BRANCH_SHORT_HASH}..${COMMIT_SHORT_HASH}\n"
  git update-ref -m "merge ${COMMIT}: Fast forward" "refs/heads/${BRANCH}" \
                    "${COMMIT_HASH}" "${BRANCH_HASH}"
  if [ $? -ne 0 ]; then
    printf 'Error: fast forward using update-ref failed\n' >&2
    return 4
  fi
  printf 'Fast forward\n'
  git --no-pager diff --stat "${BRANCH}@{1}" "${BRANCH}"
  [ $? -eq 0 ] || printf 'Warning: "git diff" failed\n'
}

#------------------------------------------------------------------------------

function run_with_stderr_logging {
  local STDERR_FILE="$1"
  shift
  # The sequence "3>&1 1>&2 2>&3" swaps stdout and stderr
  # The usage of a sub-shell allows swapping them back after "tee" invocation
  ("$@" 3>&1 1>&2 2>&3 | /usr/bin/tee "${STDERR_FILE}") 3>&1 1>&2 2>&3
}

#------------------------------------------------------------------------------

function read_branch_config {
  local BRANCH="$1"
  local GIT_ERRORS_FILE="$2"
  run_with_stderr_logging "${GIT_ERRORS_FILE}" git --no-pager show \
        "remotes/origin/${BRANCH}:branch.config"
  if [ $? -ne 0 ]; then
    exit $?
  fi
}

#------------------------------------------------------------------------------

# Avoid problem with "strange" user settigns ...
unset ENV
export PS1='$ '

unset GIT_AUTHOR FINAL_BRANCH RUN NON_INTERACTIVE STOP_AT_BRANCH STOP_AT_FLAG
unset BACKWARD_TO EDIT_MERGE M_FLAG
for ARG in "$@"; do
  [ "${M_FLAG}" = '1' ] && M_FLAG=2
  case "${ARG}" in
    -\?|-h|-help|--help) Usage 0 ;;
    -m) M_FLAG=1 ;;
    -author=*) GIT_AUTHOR=${ARG#-author=}
               GITCFG="/users/${GIT_AUTHOR}/.gitconfig"
               GITNAME=$(/bin/awk '/^[ \t]*name[ \t]*=/{ print $3,$4 }' ${GITCFG})
               GITMAIL=$(/bin/awk '/^[ \t]*email[ \t]*=/{ print $3 }' ${GITCFG})
               GIT_AUTHOR="--author=${GITNAME} <${GITMAIL}>"
               unset GITCFG GITNAME GITMAIL ;;
    -stay=*) FINAL_BRANCH=${ARG#-stay=} ;;
    --test) RUN=echo ;;
    --no-interact) NON_INTERACTIVE=1 ;;
    --already-in=*) STOP_AT_BRANCH=${ARG#--already-in=}
                    STOP_AT_FLAG='X' ;;
    --skip-from=*) STOP_AT_BRANCH=${ARG#--skip-from=}
                   STOP_AT_FLAG='s' ;;
    --backward=*) BACKWARD_TO=${ARG#--backward=} ;;
    --edit) EDIT_MERGE=1 ;;
    -*) printf 'Unknown option "%s" !\n' "${ARG}" >&2
        Usage 1 ;;
    *) if [ "${M_FLAG}" = '2' ]; then
         MESSAGE="${ARG}"
         unset M_FLAG
       else
         printf 'Unknown argument "%s" (forgot "-m" ?) !\n' "${ARG}" >&2
         Usage 2
       fi
  esac
done
if [ "${M_FLAG}" ]; then
  printf 'Missing argument after "-m" !\n' >&2
  Usage 3
fi
unset M_FLAG

# Check commit message ...
if [ -z "${MESSAGE}" ]; then
  MESSAGE=$(git --no-pager log -1 --pretty=format:%s%n | \
            /bin/sed -e 's/Merged* [^ ]* into [^ ]* (//' -e 's/ *)$//')
fi
while /bin/true; do
  printf 'The following commit-message will be used:\n\t[1;7m%s[m\n' \
         "${MESSAGE}"
  ask_for_confirmation 'Do you confirm the message ?' '-force'
  [ $? -eq 0 ] && break # If answer is 'Y', stop loop
  unset MESSAGE
  while [ -z "${MESSAGE}" ]; do
    printf 'Insert a commit-message (CTRL-C to abort) : '
    read MESSAGE
  done
done

ACTIVE=$(git --no-pager branch | /bin/grep '^\*' | \
         /bin/sed -e 's/\* //' -e 's///')

START_BR="${ACTIVE}"
if [ "${BACKWARD_TO}" ]; then
  if [ -z "${STOP_AT_BRANCH}" ]; then
    printf '\tProcess will stop (with "merge -%s ours") at branch "%s".\n' \
           "${STOP_AT_FLAG}" "${ACTIVE}"
    STOP_AT_BRANCH="${ACTIVE}"
  fi
  START_BR="${BACKWARD_TO}"
fi

BRANCH_CONFIG_FAILURE_FILE="git_branch_config.$$.err"
> "${BRANCH_CONFIG_FAILURE_FILE}"
MATCHED=$(BR="${START_BR}"; \
          while /bin/true; do \
            BR=$(read_branch_config "${BR}" "${BRANCH_CONFIG_FAILURE_FILE}" | \
                 /bin/awk '/^[ \t]*NEXT/{ print $3 }'); \
            [ -z "${BR}" -o "${BR}" = 'none' -o "${BR}" = 'master' ] && break; \
            printf '%s ' "${BR}"; \
            [ "${BR}" = "${STOP_AT_BRANCH}" ] && break; \
          done)
if [ -s "${BRANCH_CONFIG_FAILURE_FILE}" ]; then
  /bin/rm -f "${BRANCH_CONFIG_FAILURE_FILE}"
  printf '\n\tCannot read config file for some branch:\n\t%s !\n' \
         'try "git align-branches" first' >&2
  exit 4
fi
MATCHED=${MATCHED% }
LAST_BRANCH=${MATCHED##* }
NEXT_OF_LAST=$(read_branch_config "${LAST_BRANCH}" "${BRANCH_CONFIG_FAILURE_FILE}" | \
               /bin/awk '/^[ \t]*NEXT/{ print $3 }');
unset UPDATE_MASTER_BRANCH
if [ "${NEXT_OF_LAST}" = 'master' ]; then
  UPDATE_MASTER_BRANCH=1
fi
unset LAST_BRANCH NEXT_OF_LAST

CURRENT=$(read_branch_config "${START_BR}" "${BRANCH_CONFIG_FAILURE_FILE}" | \
          /bin/awk '/^[ \t]*CURRENT/{ print $3 }')
/bin/rm -f "${BRANCH_CONFIG_FAILURE_FILE}"

if [ -z "${BACKWARD_TO}" ]; then
  # Check for (local) user's branch ...
  if [ "${ACTIVE}" != "${CURRENT}" ]; then
    printf 'WARNING: current branch "%s" appears to be a sub-branch of "%s".\n' \
           "${ACTIVE}" "${CURRENT}" >&2
    ask_for_confirmation "Do you want to merge '${ACTIVE}' into '${CURRENT}' ?" \
                         '-force'
    if [ $? -eq 0 ]; then # Answer is 'Y'
      MATCHED="${CURRENT} ${MATCHED}"
    else # Answer is 'N'
      printf 'Command aborted as requested.\n'
      exit 0
    fi
  fi
fi

if [ "${BACKWARD_TO}" ]; then
  Info "Cherry-picking last commit into branch '${BACKWARD_TO}'"
  COMMIT_ID=$(git --no-pager log -1 --pretty=format:%H)
  SHORT_COMMIT=$(echo "${COMMIT_ID}" | /usr/bin/cut -c1-7)
  ask_for_confirmation "Do you want to cherry-pick commit '${SHORT_COMMIT}' ?" \
                       '-force'
  if [ $? -eq 0 ]; then # Answer is 'Y'
    SubInfo "Running 'git checkout ${BACKWARD_TO}'"
    git checkout "${BACKWARD_TO}"
    SubInfo "Running 'git cherry-pick'"
    git cherry-pick --no-commit "${COMMIT_ID}"
    SubInfo "Showing 'git status'"
    ${RUN} git status -uno
    SubInfo "Running 'git mergetool' if needed"
    ${RUN} git mergetool
    SubInfo "Running 'git commit' to conclude merge"
    run_git_commit "cherry-pick of ${SHORT_COMMIT} (${MSG})"
  else # Answer is 'N'
    printf 'Command aborted as requested.\n'
    exit 0
  fi
fi

if [ -z "${MATCHED}" ]; then
  Info "No next branch to merge"
  ask_for_confirmation 'Do you want to push current branch ?' '-force'
  if [ $? -eq 0 ]; then # Answer is 'Y'
    SubInfo "Running 'git push'"
    ${RUN} git push
    if [ $? -ne 0 ]; then
      SubInfo "Push failed: trying a 'git pull' first"
      ${RUN} git pull --no-commit
      SubInfo "Commiting the pull merge"
      REMOTE=$(git remote -v | \
               /bin/awk '/(fetch)/{ sub("^.*@",""); sub("\\..*",""); print }')
      run_git_commit "Merge remote branch ${ACTIVE} of ${REMOTE} into ${ACTIVE} (${MESSAGE})"
      SubInfo "Running 'git push' again"
      ${RUN} git push
    fi

    if [ "${UPDATE_MASTER_BRANCH}" ]; then
      BR='master'
      SubInfo "Fast-forwarding '${ACTIVE}' --> '${BR}'"
      git_ff_merge "${BR}" "${ACTIVE}"
      if [ $? -eq 0 ]; then
        SubInfo "Running 'git push ${BR}'"
        ${RUN} git push origin "${BR}"
      fi
    fi
  else # Answer is 'N'
    printf "Manually run '[1;7m%s[m'\n" 'git push'
  fi
else
  Info "Pulling branches from remote repository"
  SubInfo "Running 'git align-branches ${MATCHED}'"
  ${RUN} git align-branches ${MATCHED}
  if [ $? -ne 0 ]; then
    printf '\n\tERROR: git align-branches failed !\n\n' >&2
    exit 1
  fi

  PREV=${ACTIVE}
  for BR in ${MATCHED}; do
    unset MERGE_OPT
    MERGE_TYPE='Merg'
    if [ "${BR}" = "${STOP_AT_BRANCH}" ]; then
       MERGE_OPT=" -${STOP_AT_FLAG} ours"
       MERGE_TYPE='(No)merg'
    fi
    Info "${MERGE_TYPE}ing '${PREV}' --> '${BR}'[33m${MERGE_OPT}[30m"
    do_git_merge "${BR}" "${PREV}" "${MESSAGE}" "${MERGE_TYPE}" "${MERGE_OPT}"
    #[ "${BR}" = "${STOP_AT_BRANCH}" ] && break
    PREV="${BR}"
  done
  if [ -z "${STOP_AT_BRANCH}" -a "${UPDATE_MASTER_BRANCH}" ]; then
    BR='master'
    Info "Fast-forwarding '${PREV}' --> '${BR}'"
    git_ff_merge "${BR}" "${PREV}"
  fi

  FINAL_OR_ORIGINAL='final'
  if [ -z "${FINAL_BRANCH}" ]; then
    FINAL_BRANCH="${ACTIVE}"
    FINAL_OR_ORIGINAL='original'
  fi
  Info "Reverting back to ${FINAL_OR_ORIGINAL} branch '${FINAL_BRANCH}'"
  SubInfo "Running 'git checkout ${FINAL_BRANCH}'"
  ${RUN} git checkout ${FINAL_BRANCH}

  Info "Pushing all branches to remote repository"
  printf '\nYou shall now push all changed branches to the remote repository.\n'
  ask_for_confirmation 'Proceed with push ?' '-force'
  if [ $? -eq 0 ]; then # Answer is 'Y'
    SubInfo "Running 'git align-branches --push ${ACTIVE} ${MATCHED}'"
    ${RUN} git align-branches --push ${ACTIVE} ${MATCHED}
    if [ $? -ne 0 ]; then
      printf '\n\tERROR: git align-branches --push failed !\n\n' >&2
      exit 5
    fi

    if [ -z "${STOP_AT_BRANCH}" -a "${UPDATE_MASTER_BRANCH}" ]; then
      BR='master'
      SubInfo "Fast-forwarding '${PREV}' --> '${BR}' again"
      git_ff_merge "${BR}" "${PREV}"
      if [ $? -eq 0 ]; then
        SubInfo "Running 'git push ${BR}'"
        ${RUN} git push origin "${BR}"
      fi
    fi
  else # Answer is 'N'
    printf "Manually run '[1;7m%s[m'\n" \
           "git align-branches --push ${ACTIVE} ${MATCHED}"
  fi
fi
